[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"

[[redirects]]
  from = "https://virkhanna.net/*"
  to = "https://vir.codes/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.virkhanna.net/*"
  to = "https://vir.codes/:splat"
  status = 301
  force = true
